AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PhotoOpsAI central application platform

Parameters:
  ServiceName:
    Type: String
    Description: "Name of service"

  ServiceEnv:
    Type: String
    Description: "Name of deployment environment"
    Default: "prime"

  LogLevel:
    Type: String
    Description: "Log level for functions; used internally in code."
    Default: 'INFO'
    AllowedValues:
      - 'DEBUG'
      - 'INFO'
      - 'WARNING'
      - 'ERROR'
      - 'CRITICAL'

  XRayTracingMode:
    Type: String
    Description: "AWS XRay tracing mode"
    Default: PassThrough
    AllowedValues:
      - Active
      - PassThrough


Globals:
  Function:
    Environment:
      Variables:
        LOG_LEVEL:
          Ref: LogLevel
        POWERTOOLS_SERVICE_NAME: !Ref AWS::StackName
    Tracing: !Ref XRayTracingMode


Resources:
  # Layer also brings in aws-lambda-powertools and boto3
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "${AWS::StackName}-${ServiceEnv}-CommonLayer"
      ContentUri: src/common
      RetentionPolicy: Delete
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: makefile

  CommonLayerArnSsmParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /layers/${AWS::StackName}/CommonLayerArn
      Type: String
      Value: !Ref CommonLayer
      Description: ARN of PhotoOps Common Lambda layer for Python 3.8


  IngestS3Event:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Ingest an S3 event"
      CodeUri: src/handlers/IngestS3Event
      Handler: function.handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 3
      Layers:
        - !Ref CommonLayer
      Events:
        SnsEvent:
          Type: SNS
          Properties:
            Topic: !Ref PhotoOpsIngestTopic
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: EventBridge
            Destination: !GetAtt EventBus.Arn
          OnFailure:
            Type: 'SQS'
            Destination: !GetAtt IngestS3EventDlqQueue.Arn


  IngestS3EventDlqQueue:
    Type: AWS::SQS::Queue


  # FIXME: Running close to memory limit but don't want to bump memory up for
  # all transactions. Possibly we create small, medium, and large functions
  # where we use the object size in the S3 event as a determining factor for
  # which function gets invoked.
  GetExifData:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Get EXIF data"
      CodeUri: src/handlers/GetExifData
      Handler: function.handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 30
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          CROSS_ACCOUNT_IAM_ROLE_ARN: !GetAtt PhotoOpsCrossAccountIamRole.Arn
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Sid: StsAssumeRole
              Effect: Allow
              Action:
                - sts:AssumeRole
              Resource: !GetAtt PhotoOpsCrossAccountIamRole.Arn
      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref EventBus
            InputPath: "$.detail.responsePayload"
            Pattern:
              source: [ "lambda" ]
              detail-type: [ "Lambda Function Invocation Result - Success" ]
              detail:
                requestPayload:
                  Records:
                    Sns:
                      TopicArn: [ !Ref PhotoOpsIngestTopic ]
                responsePayload:
                  Records:
                    eventSource: [ "aws:s3" ]
                    # FIXME: Is this all the possible event names?
                    eventName:
                      - prefix: "ObjectCreated:"
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: EventBridge
            Destination: !GetAtt EventBus.Arn
          OnFailure:
            Type: 'SQS'
            Destination: !GetAtt GetExifDataDlqQueue.Arn

  GetExifDataDlqQueue:
    Type: AWS::SQS::Queue


  GetExifCameraData:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Get EXIF camera data"
      CodeUri: src/handlers/GetExifCameraData
      Handler: function.handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 3
      Layers:
        - !Ref CommonLayer
      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref EventBus
            InputPath: "$.detail.responsePayload.Item"
            Pattern:
              source: [ "lambda" ]
              detail-type: [ "Lambda Function Invocation Result - Success" ]
              detail:
                responsePayload:
                  Item:
                    pk:
                      - exists: true
                    sk:
                      - 'exif#v0'
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: EventBridge
            Destination: !GetAtt EventBus.Arn
          OnFailure:
            Type: 'SQS'
            Destination: !GetAtt GetExifCameraDataDlqQueue.Arn

  GetExifCameraDataDlqQueue:
    Type: AWS::SQS::Queue


  GetExifLensData:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Get EXIF lens data"
      CodeUri: src/handlers/GetExifLensData
      Handler: function.handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 3
      Layers:
        - !Ref CommonLayer
      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref EventBus
            InputPath: "$.detail.responsePayload.Item"
            Pattern:
              source: [ "lambda" ]
              detail-type: [ "Lambda Function Invocation Result - Success" ]
              detail:
                responsePayload:
                  Item:
                    pk:
                      - exists: true
                    sk:
                      - 'exif#v0'
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: EventBridge
            Destination: !GetAtt EventBus.Arn
          OnFailure:
            Type: 'SQS'
            Destination: !GetAtt GetExifLensDataDlqQueue.Arn

  GetExifLensDataDlqQueue:
    Type: AWS::SQS::Queue


  GetExifImageData:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Get EXIF image data"
      CodeUri: src/handlers/GetExifImageData
      Handler: function.handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 3
      Layers:
        - !Ref CommonLayer
      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref EventBus
            InputPath: "$.detail.responsePayload.Item"
            Pattern:
              source: [ "lambda" ]
              detail-type: [ "Lambda Function Invocation Result - Success" ]
              detail:
                responsePayload:
                  Item:
                    pk:
                      - exists: true
                    sk:
                      - 'exif#v0'
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: EventBridge
            Destination: !GetAtt EventBus.Arn
          OnFailure:
            Type: 'SQS'
            Destination: !GetAtt GetExifImageDataDlqQueue.Arn

  GetExifImageDataDlqQueue:
    Type: AWS::SQS::Queue


  GetExifLocationData:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Get EXIF location data"
      CodeUri: src/handlers/GetExifLocationData
      Handler: function.handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 3
      Layers:
        - !Ref CommonLayer
      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref EventBus
            InputPath: "$.detail.responsePayload.Item"
            Pattern:
              source: [ "lambda" ]
              detail-type: [ "Lambda Function Invocation Result - Success" ]
              detail:
                responsePayload:
                  Item:
                    pk:
                      - exists: true
                    sk:
                      - 'exif#v0'
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: EventBridge
            Destination: !GetAtt EventBus.Arn
          OnFailure:
            Type: 'SQS'
            Destination: !GetAtt GetExifLocationDataDlqQueue.Arn

  GetExifLocationDataDlqQueue:
    Type: AWS::SQS::Queue


  GetFileData:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Get file data"
      CodeUri: src/handlers/GetFileData
      Handler: function.handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 3
      Layers:
        - !Ref CommonLayer
      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref EventBus
            InputPath: "$.detail.responsePayload.Item"
            Pattern:
              source: [ "lambda" ]
              detail-type: [ "Lambda Function Invocation Result - Success" ]
              detail:
                responsePayload:
                  Item:
                    pk:
                      - exists: true
                    sk:
                      - 'exif#v0'
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: EventBridge
            Destination: !GetAtt EventBus.Arn
          OnFailure:
            Type: 'SQS'
            Destination: !GetAtt GetFileDataDlqQueue.Arn

  GetFileDataDlqQueue:
    Type: AWS::SQS::Queue


  PutDdbItem:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Put a DDB Item"
      CodeUri: src/handlers/PutDdbItem
      Handler: function.handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 3
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          DDB_TABLE_NAME: !Ref DynamoDBTable
      Policies:
        - Statement:
          - Effect: "Allow"
            Action:
              - "dynamodb:PutItem"
              - "dynamodb:UpdateItem"
            Resource: !GetAtt DynamoDBTable.Arn
      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref EventBus
            InputPath: "$.detail.responsePayload"
            Pattern:
              source: [ "lambda" ]
              detail-type: [ "Lambda Function Invocation Result - Success" ]
              detail:
                responsePayload:
                  Item:
                    pk:
                      - exists: true
                    sk:
                      - exists: true
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: EventBridge
            Destination: !GetAtt EventBus.Arn
          OnFailure:
            Type: 'SQS'
            Destination: !GetAtt PutDdbItemDlqQueue.Arn

  PutDdbItemDlqQueue:
    Type: AWS::SQS::Queue


  PhotoOpsIngestTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${AWS::StackName}-PhotoOpsIngestTopic"

  PhotoOpsIngestTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: "PhotoOpsIngestTopicPolicy"
        Version: "2012-10-17"
        Statement:
        - Sid: "GlobalWrite"
          Effect: Allow
          Principal:
            AWS: "*"
          Action: sns:Publish
          Resource: !Ref PhotoOpsIngestTopic
      Topics:
        - !Ref PhotoOpsIngestTopic


  CreateJpegFromRaw:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Create a CreateJpegFromRaw"
      CodeUri: src/handlers/CreateJpegFromRaw
      Handler: function.handler
      Runtime: python3.8
      MemorySize: 512
      Timeout: 30
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          PHOTOOPS_S3_BUCKET: !Ref PhotoOpsBucket
          CROSS_ACCOUNT_IAM_ROLE_ARN: !GetAtt PhotoOpsCrossAccountIamRole.Arn
      Policies:
        - Statement:
          - Sid: StsAssumeRole
            Effect: Allow
            Action:
              - sts:AssumeRole
            Resource: !GetAtt PhotoOpsCrossAccountIamRole.Arn
        - Statement:
          - Sid: S3PutObject
            Effect: "Allow"
            Action:
              - s3:PutObject
            Resource: !Sub "${PhotoOpsBucket.Arn}/*"
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: EventBridge
            Destination: !GetAtt EventBus.Arn
          OnFailure:
            Type: 'SQS'
            Destination: !GetAtt CreateJpegFromRawDlqQueue.Arn

  CreateJpegFromRawDlqQueue:
    Type: AWS::SQS::Queue

  PhotoOpsBucket:
    Type: AWS::S3::Bucket


  PhotoOpsCrossAccountIamRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "CrossAccountAccess-${ServiceEnv}"
      Path: "/PhotoOpsAI/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS:
                # Anyone in account can assume so long as they have their own
                # permission to assume the role.
                - !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "DownloadS3Object"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: "GetS3Object"
                Effect: "Allow"
                Action:
                  - "s3:GetObject"
                Resource: "arn:aws:s3:::*/*"
              - Sid: "ListS3Bucket"
                Effect: "Allow"
                Action:
                  - "s3:ListBucket"
                Resource: "arn:aws:s3:::*/"


  # FIXME: Need a DLQ
  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub "${ServiceName}-${ServiceEnv}"

  EventBusLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/events/${EventBus}/all"
      RetentionInDays: 7

  EventBusLogGroupRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Log all events to CloudWatch"
      EventBusName: !Ref EventBus
      EventPattern:
        account:
          - !Ref AWS::AccountId
      Targets:
        - Arn: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${EventBusLogGroup}"
          Id: "EventBusLogGroup"


  # Grant eventBus ability to deliver logs to CW.
  #
  # ref: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/351#issuecomment-887045751
  LogGroupForEventsPolicy:
    Type: AWS::Logs::ResourcePolicy
    Properties:
      PolicyName: !Sub "${AWS::StackName}-${ServiceEnv}-EventBridgeToCWLogsPolicy"
      PolicyDocument: !Sub
        - >
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Sid": "EventBridgetoCWLogsPolicy",
                "Effect": "Allow",
                "Principal": {
                  "Service": [
                    "delivery.logs.amazonaws.com",
                    "events.amazonaws.com"
                  ]
                },
                "Action": [
                  "logs:CreateLogStream",
                  "logs:PutLogEvents"
                ],
                "Resource": [
                  "${logArn}"
                ],
                "Condition": {
                  "ArnEquals": {"aws:SourceArn": "${ruleArn}"}
                }
              }
            ]
          }
        - { logArn: !GetAtt EventBusLogGroup.Arn, ruleArn:  !GetAtt EventBusLogGroupRule.Arn}



  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    # NOTE: Retain data by default
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
        - AttributeName: "sk"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
        - AttributeName: "sk"
          KeyType: "RANGE"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      BillingMode: "PAY_PER_REQUEST"


  # For CloudWatch Alarms
  CloudWatchTopic:
    Type: AWS::SNS::Topic


  # SSM Parameters
  PhotoOpsIngestTopicArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/PhotoOpsAI/${ServiceName}/${ServiceEnv}/PhotoOpsIngestTopicArn"
      Type: String
      Description: "Ingest SNS topic ARN"
      Value: !Ref PhotoOpsIngestTopic

  PhotoOpsBucketName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/PhotoOpsAI/${ServiceName}/${ServiceEnv}/PhotoOpsBucketName"
      Type: String
      Description: "Name of PhotoOps image bucket"
      Value: !Ref PhotoOpsBucket

  DynamoDBTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/PhotoOpsAI/${ServiceName}/${ServiceEnv}/DynamoDBTableName"
      Type: String
      Description: "DDB table name"
      Value: !Ref DynamoDBTable

  DynamoDBTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/PhotoOpsAI/${ServiceName}/${ServiceEnv}/DynamoDBTableArn"
      Type: String
      Description: "DDB table ARN"
      Value: !GetAtt DynamoDBTable.Arn

  EventBusArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/PhotoOpsAI/${ServiceName}/${ServiceEnv}/EventBusArn"
      Type: String
      Description: "Event Bus ARN"
      Value: !GetAtt EventBus.Arn

  EventBusName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/PhotoOpsAI/${ServiceName}/${ServiceEnv}/EventBusName"
      Type: String
      Description: "Event Bus Name"
      Value: !Ref EventBus

  CloudWatchTopicArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/PhotoOpsAI/${ServiceName}/${ServiceEnv}/CloudWatchTopicArn"
      Type: String
      Description: "CloudWatch SNS Topic ARN"
      Value: !Ref CloudWatchTopic

Outputs:
  PhotoOpsIngestTopicArn:
    Description: "ARN of PhotoOps Ingest topic ARN"
    Value: !Ref PhotoOpsIngestTopic

  DynamoDBTableName:
    Description: "Name of DynamoDB table"
    Value: !Ref DynamoDBTable

  EventBusArn:
    Description: "ARN of event bus"
    Value: !GetAtt EventBus.Arn

  EventBusName:
    Description: "Name of event bus"
    Value: !Ref EventBus

  CloudWatchTopicArn:
    Description: "ARN of CloudWatch topic"
    Value: !Ref CloudWatchTopic

