AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PhotoOpsAI central application platform

Parameters:
  ServiceName:
    Type: String
    Description: "Name of service"
    Default: "PhotoOps"

  ServiceEnv:
    Type: String
    Description: "Name of deployment environment"
    Default: "prime"

  LogLevel:
    Type: String
    Description: "Log level for functions; used internally in code."
    Default: 'INFO'
    AllowedValues:
      - 'DEBUG'
      - 'INFO'
      - 'WARNING'
      - 'ERROR'
      - 'CRITICAL'

  XRaySDKEnabled:
    Type: String
    Description: "AWS X-RAY SDK enabled"
    Default: 'Disabled'
    AllowedValues:
      - 'Enabled'
      - 'Disabled'

  XRayTracingMode:
    Type: String
    Description: "AWS XRay tracing mode"
    Default: PassThrough
    AllowedValues:
      - Active
      - PassThrough



Mappings:
  XRaySDKEnabled:
    Enabled:
      Enabled: "true"
    Disabled:
      Enabled: "false"

Globals:
  Function:
    Environment:
      Variables:
        LOG_LEVEL:
          Ref: LogLevel
        AWS_XRAY_SDK_ENABLED:
          Fn::FindInMap:
            - XRaySDKEnabled
            - Ref: XRaySDKEnabled
            - Enabled
    Tags:
      ServiceName: !Ref ServiceName
      ServiceEnv: !Ref ServiceEnv
    Tracing: !Ref XRayTracingMode


Resources:
  IngestS3Event:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Ingest an S3 event"
      CodeUri: src/handlers/IngestS3Event
      Handler: function.handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 3
      DeadLetterQueue:
        Type: 'SQS'
        TargetArn: !GetAtt IngestS3EventDlqQueue.Arn
      Events:
        SnsEvent:
          Type: SNS
          Properties:
            Topic: !Ref PhotoOpsIngestTopic
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: EventBridge
            Destination: !GetAtt EventBus.Arn

  IngestS3EventDlqQueue:
    Type: AWS::SQS::Queue


  PhotoOpsIngestTopic:
    Type: AWS::SNS::Topic

  PhotoOpsIngestTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: "PhotoOpsIngestTopicPolicy"
        Version: "2012-10-17"
        Statement:
        - Sid: "GlobalWrite"
          Effect: Allow
          Principal:
            AWS: "*"
          Action: sns:Publish
          Resource: !Ref PhotoOpsIngestTopic
      Topics:
        - !Ref PhotoOpsIngestTopic


  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub "${ServiceName}-${ServiceEnv}"

  EventBusLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/eventbus/${EventBus}/all"
      RetentionInDays: 7

  EventBusLogGroupRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Log all events to CloudWatch"
      EventBusName: !Ref EventBus
      EventPattern:
        account:
          - !Ref AWS::AccountId
      Targets:
        - Arn: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${EventBusLogGroup}"
          Id: "EventBusLogGroup"


  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    # NOTE: Retain data by default
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
        - AttributeName: "sk"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
        - AttributeName: "sk"
          KeyType: "RANGE"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      BillingMode: "PAY_PER_REQUEST"


  # For CloudWatch Alarms
  CloudWatchTopic:
    Type: AWS::SNS::Topic


  # SSM Parameters
  PhotoOpsIngestTopicArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/PhotoOpsAI/${ServiceName}/${ServiceEnv}/PhotoOpsIngestTopicArn"
      Type: String
      Description: "Ingest SNS topic ARN"
      Value: !Ref PhotoOpsIngestTopic

  DynamoDBTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/PhotoOpsAI/${ServiceName}/${ServiceEnv}/DynamoDBTableName"
      Type: String
      Description: "DDB table name"
      Value: !Ref DynamoDBTable

  EventBusArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/PhotoOpsAI/${ServiceName}/${ServiceEnv}/EventBusArn"
      Type: String
      Description: "Event Bus ARN"
      Value: !GetAtt EventBus.Arn

  EventBusName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/PhotoOpsAI/${ServiceName}/${ServiceEnv}/EventBusName"
      Type: String
      Description: "Event Bus Name"
      Value: !Ref EventBus

  CloudWatchTopicArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/PhotoOpsAI/${ServiceName}/${ServiceEnv}/CloudWatchTopicArn"
      Type: String
      Description: "CloudWatch SNS Topic ARN"
      Value: !Ref CloudWatchTopic

Outputs:
  PhotoOpsIngestTopicArn:
    Description: "ARN of PhotoOps Ingest topic ARN"
    Value: !Ref PhotoOpsIngestTopic

  DynamoDBTableName:
    Description: "Name of DynamoDB table"
    Value: !Ref DynamoDBTable

  EventBusArn:
    Description: "ARN of event bus"
    Value: !GetAtt EventBus.Arn

  EventBusName:
    Description: "Name of event bus"
    Value: !Ref EventBus

  CloudWatchTopicArn:
    Description: "ARN of CloudWatch topic"
    Value: !Ref CloudWatchTopic

